from distutils.core import setup

setup(
    name='grata',
    version='0.0.1',
    packages=['', 'src', 'src.routes', 'src.handlers', '.venv.lib.python3.6.distutils', '.venv.lib.python3.6.encodings',
              '.venv.lib.python3.6.importlib', '.venv.lib.python3.6.collections',
              '.venv.lib.python3.6.site-packages.pip', '.venv.lib.python3.6.site-packages.pip._vendor',
              '.venv.lib.python3.6.site-packages.pip._vendor.idna',
              '.venv.lib.python3.6.site-packages.pip._vendor.pep517',
              '.venv.lib.python3.6.site-packages.pip._vendor.pytoml',
              '.venv.lib.python3.6.site-packages.pip._vendor.certifi',
              '.venv.lib.python3.6.site-packages.pip._vendor.chardet',
              '.venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              '.venv.lib.python3.6.site-packages.pip._vendor.distlib',
              '.venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              '.venv.lib.python3.6.site-packages.pip._vendor.msgpack',
              '.venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              '.venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              '.venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              '.venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              '.venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              '.venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              '.venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              '.venv.lib.python3.6.site-packages.pip._vendor.colorama',
              '.venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              '.venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              '.venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              '.venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              '.venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              '.venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              '.venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              '.venv.lib.python3.6.site-packages.pip._vendor.progress',
              '.venv.lib.python3.6.site-packages.pip._vendor.requests',
              '.venv.lib.python3.6.site-packages.pip._vendor.packaging',
              '.venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              '.venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              '.venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              '.venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              '.venv.lib.python3.6.site-packages.pip._internal', '.venv.lib.python3.6.site-packages.pip._internal.cli',
              '.venv.lib.python3.6.site-packages.pip._internal.req',
              '.venv.lib.python3.6.site-packages.pip._internal.vcs',
              '.venv.lib.python3.6.site-packages.pip._internal.utils',
              '.venv.lib.python3.6.site-packages.pip._internal.models',
              '.venv.lib.python3.6.site-packages.pip._internal.commands',
              '.venv.lib.python3.6.site-packages.pip._internal.operations', '.venv.lib.python3.6.site-packages.attr',
              '.venv.lib.python3.6.site-packages.idna', '.venv.lib.python3.6.site-packages.yarl',
              '.venv.lib.python3.6.site-packages.tests', '.venv.lib.python3.6.site-packages.tests.client',
              '.venv.lib.python3.6.site-packages.tests.router', '.venv.lib.python3.6.site-packages.tests.templates',
              '.venv.lib.python3.6.site-packages.wheel', '.venv.lib.python3.6.site-packages.wheel.cli',
              '.venv.lib.python3.6.site-packages.Cython', '.venv.lib.python3.6.site-packages.Cython.Plex',
              '.venv.lib.python3.6.site-packages.Cython.Build', '.venv.lib.python3.6.site-packages.Cython.Build.Tests',
              '.venv.lib.python3.6.site-packages.Cython.Tests', '.venv.lib.python3.6.site-packages.Cython.Runtime',
              '.venv.lib.python3.6.site-packages.Cython.Tempita', '.venv.lib.python3.6.site-packages.Cython.Utility',
              '.venv.lib.python3.6.site-packages.Cython.Compiler',
              '.venv.lib.python3.6.site-packages.Cython.Compiler.Tests',
              '.venv.lib.python3.6.site-packages.Cython.Debugger',
              '.venv.lib.python3.6.site-packages.Cython.Debugger.Tests',
              '.venv.lib.python3.6.site-packages.Cython.Distutils', '.venv.lib.python3.6.site-packages.vibora',
              '.venv.lib.python3.6.site-packages.vibora.cache', '.venv.lib.python3.6.site-packages.vibora.client',
              '.venv.lib.python3.6.site-packages.vibora.router', '.venv.lib.python3.6.site-packages.vibora.headers',
              '.venv.lib.python3.6.site-packages.vibora.parsers', '.venv.lib.python3.6.site-packages.vibora.request',
              '.venv.lib.python3.6.site-packages.vibora.schemas',
              '.venv.lib.python3.6.site-packages.vibora.schemas.extensions',
              '.venv.lib.python3.6.site-packages.vibora.workers', '.venv.lib.python3.6.site-packages.vibora.protocol',
              '.venv.lib.python3.6.site-packages.vibora.sessions', '.venv.lib.python3.6.site-packages.vibora.multipart',
              '.venv.lib.python3.6.site-packages.vibora.responses',
              '.venv.lib.python3.6.site-packages.vibora.templates',
              '.venv.lib.python3.6.site-packages.vibora.templates.compilers',
              '.venv.lib.python3.6.site-packages.vibora.components',
              '.venv.lib.python3.6.site-packages.vibora.websockets', '.venv.lib.python3.6.site-packages.aiohttp',
              '.venv.lib.python3.6.site-packages.certifi', '.venv.lib.python3.6.site-packages.chardet',
              '.venv.lib.python3.6.site-packages.chardet.cli', '.venv.lib.python3.6.site-packages.slacker',
              '.venv.lib.python3.6.site-packages.urllib3', '.venv.lib.python3.6.site-packages.urllib3.util',
              '.venv.lib.python3.6.site-packages.urllib3.contrib',
              '.venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              '.venv.lib.python3.6.site-packages.urllib3.packages',
              '.venv.lib.python3.6.site-packages.urllib3.packages.backports',
              '.venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              '.venv.lib.python3.6.site-packages.dateutil', '.venv.lib.python3.6.site-packages.dateutil.tz',
              '.venv.lib.python3.6.site-packages.dateutil.parser',
              '.venv.lib.python3.6.site-packages.dateutil.zoneinfo', '.venv.lib.python3.6.site-packages.pendulum',
              '.venv.lib.python3.6.site-packages.pendulum.tz', '.venv.lib.python3.6.site-packages.pendulum.tz.data',
              '.venv.lib.python3.6.site-packages.pendulum.tz.zoneinfo',
              '.venv.lib.python3.6.site-packages.pendulum.utils', '.venv.lib.python3.6.site-packages.pendulum.mixins',
              '.venv.lib.python3.6.site-packages.pendulum.locales',
              '.venv.lib.python3.6.site-packages.pendulum.locales.da',
              '.venv.lib.python3.6.site-packages.pendulum.locales.de',
              '.venv.lib.python3.6.site-packages.pendulum.locales.en',
              '.venv.lib.python3.6.site-packages.pendulum.locales.es',
              '.venv.lib.python3.6.site-packages.pendulum.locales.fa',
              '.venv.lib.python3.6.site-packages.pendulum.locales.fo',
              '.venv.lib.python3.6.site-packages.pendulum.locales.fr',
              '.venv.lib.python3.6.site-packages.pendulum.locales.ko',
              '.venv.lib.python3.6.site-packages.pendulum.locales.lt',
              '.venv.lib.python3.6.site-packages.pendulum.locales.zh',
              '.venv.lib.python3.6.site-packages.pendulum.locales.pt_br',
              '.venv.lib.python3.6.site-packages.pendulum.parsing',
              '.venv.lib.python3.6.site-packages.pendulum.parsing.exceptions',
              '.venv.lib.python3.6.site-packages.pendulum.formatting',
              '.venv.lib.python3.6.site-packages.pendulum._extensions', '.venv.lib.python3.6.site-packages.pytzdata',
              '.venv.lib.python3.6.site-packages.pytzdata.commands', '.venv.lib.python3.6.site-packages.requests',
              '.venv.lib.python3.6.site-packages.multidict', '.venv.lib.python3.6.site-packages.pyximport',
              '.venv.lib.python3.6.site-packages.aioslacker', '.venv.lib.python3.6.site-packages.setuptools',
              '.venv.lib.python3.6.site-packages.setuptools.extern',
              '.venv.lib.python3.6.site-packages.setuptools._vendor',
              '.venv.lib.python3.6.site-packages.setuptools._vendor.packaging',
              '.venv.lib.python3.6.site-packages.setuptools.command', '.venv.lib.python3.6.site-packages.json_logging',
              '.venv.lib.python3.6.site-packages.json_logging.framework',
              '.venv.lib.python3.6.site-packages.json_logging.framework.flask',
              '.venv.lib.python3.6.site-packages.json_logging.framework.quart',
              '.venv.lib.python3.6.site-packages.json_logging.framework.sanic',
              '.venv.lib.python3.6.site-packages.async_timeout', '.venv.lib.python3.6.site-packages.pkg_resources',
              '.venv.lib.python3.6.site-packages.pkg_resources.extern',
              '.venv.lib.python3.6.site-packages.pkg_resources._vendor',
              '.venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging', 'config', 'utilities', 'decorators'],
    url='',
    license='',
    author='raghav tandon',
    author_email='raghavtan@gmail.com',
    description=''
)
