---
name: Checkov
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Policy Compliance Evaluation
        id: checkov
        uses: raghavtan/checkov-action@master
        with:
          config_file: compliance/configs/checkov.config.yaml
          directory: checov-test
          log_level: ERROR

      - uses: peter-evans/create-or-update-comment@v1
        name: Create comment
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ env.CHECKOV_RESULTS }}
            ```
          reactions: '+1'
          token: ${{ secrets.DOCKER_GITHUB_TOKEN }}

      - uses: peter-evans/create-or-update-comment@v1
        name: Create comment
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ```
            ${{ steps.checkov.outputs.results }}
            ```
          reactions: '+1'
          token: ${{ secrets.DOCKER_GITHUB_TOKEN }}
